### ISSUE TITLE
How to Run Project Code Coverage Tests

### ISSUE THREAD

**Issue by redvelvets** [WBertan/TestReport#1]
I noticed that the configurations for 'coverage-common', 'module', or 'project' have not been applied in the build.gradle files of the submodules. So, how are these multi-module Jacoco configurations executed via the command line, for instance with ./gradlew jacocoTestReport? I need your help bro.

**Comment by WBertan** [comment]
Hey @red-velet , this project is very old, I just updated to make it run (have to remove Robolectric too), but the report is broken.

I would suggest to use [Kover](https://github.com/Kotlin/kotlinx-kover), way better experience than using JaCoCo directly.

But to answer your question, the config for the submodules is done via these files:

```
coverage-common.gradle
coverage-module.gradle
coverage-project.gradle
```

It uses at the top level the `subprojects` to configure it. Nowadays, a better experience is to also use the `buildSrc` and use Kotlin DSL rather than gradle directly.

I will archive this repo, as all is broken and doesn't fit for the purpose anymore. I may, in the future, do a new one, similar, with the latest tools and best practices.
